%YAML:1.0

System.SaveAtlasToFile: "/home/koksyuen/Documents/fyp2/fyp_result/map"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera.fx: 381.50091715225676
Camera.fy: 380.6841806683357
Camera.cx: 321.71880735049814
Camera.cy: 239.39601119612195

# distortion parameters
Camera.k1: -0.002546507979782821
Camera.k2: -0.0019901595883390177
Camera.p1: 0.0013933664140284017
Camera.p2: -0.0016382762604292916

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 381.50091715225676
Camera2.fy: 380.6841806683357
Camera2.cx: 321.71880735049814
Camera2cy: 239.39601119612195

# distortion parameters
Camera2.k1: -0.002546507979782821
Camera2.k2: -0.0019901595883390177
Camera2.p1: 0.0013933664140284017
Camera2.p2: -0.0016382762604292916

Tlr: !!opencv-matrix
  rows: 3
  cols: 4
  dt: f
  data: [1.0, 0.0, 0.0, 0.0499585,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]


# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Image scale, it changes the image size to be processed (<1.0: reduce, >1.0: increase)
Camera.imageScale: 0.5 # 0.5 #0.7071 # 1/sqrt(2)

# Close/Far threshold. Baseline times.
ThDepth: 40.0
# stereo baseline times fx
Camera.bf: 19.114771561

#from: /home/koksyuen/Documents/fyp2/fyp_result/calibration/result/latest_imu_test1/imu_test1-camchain-imucam.yaml
# Transformation from body-frame (imu) to left camera
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.9999675687511974, 0.0046845093942410425, 0.0065510928518236035, -0.0011125128382533298,
          -0.004323631730426334, -0.9985285531854201, 0.054055847806597196, 0.009491959331157939,
          0.006794678393978443, 0.054025770195024664, 0.9985164237509344, 0.0053041758083287975,
          0.0, 0.0, 0.0, 1.0]

# Do not insert KFs when recently lost
InsertKFsWhenLost: 0

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 1.094e-02 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 1.85e-03 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 5.897e-04 # rad/s^1.5
IMU.AccWalk: 2.548e-05 # m/s^2.5
IMU.Frequency: 200

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500
Viewer.imageViewScale: 0.5
